# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(239, 351)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(0, 150, 61, 51))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 150, 61, 51))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 150, 61, 51))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(60, 200, 61, 51))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(120, 200, 61, 51))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 200, 61, 51))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 250, 61, 51))
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 250, 61, 51))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(60, 250, 61, 51))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(180, 200, 61, 51))
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"    background-color: #5be3a8;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(180, 150, 61, 51))
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"    background-color: #5be3a8;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(180, 250, 61, 51))
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"    background-color: #5be3a8;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(120, 100, 61, 51))
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"    background-color: #5be3a8;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(180, 100, 61, 51))
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"    background-color: #5be3a8;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(60, 100, 61, 51))
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"    background-color: #5be3a8;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 100, 61, 51))
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"    background-color: #5be3a8;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_17 = QtWidgets.QPushButton(Dialog)
        self.pushButton_17.setGeometry(QtCore.QRect(60, 300, 61, 51))
        self.pushButton_17.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Dialog)
        self.pushButton_18.setGeometry(QtCore.QRect(120, 300, 61, 51))
        self.pushButton_18.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(Dialog)
        self.pushButton_19.setGeometry(QtCore.QRect(180, 300, 61, 51))
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"    background-color: #169431;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #39a851;\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(0, 300, 61, 51))
        self.pushButton_20.setStyleSheet("QPushButton {\n"
"    background-color: #a8ffd9;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: #5cffb8;\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 241, 101))
        self.label.setStyleSheet("background-color: #ffffff;\n"
"font: 28pt \"MS UI Gothic\";\n"
"padding-left: 10px;")
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Calculator", "Calculator"))
        self.pushButton.setText(_translate("Dialog", "1"))
        self.pushButton_2.setText(_translate("Dialog", "2"))
        self.pushButton_3.setText(_translate("Dialog", "3"))
        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_9.setText(_translate("Dialog", "9"))
        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_8.setText(_translate("Dialog", "8"))
        self.pushButton_14.setText(_translate("Dialog", "-"))
        self.pushButton_15.setText(_translate("Dialog", "x"))
        self.pushButton_16.setText(_translate("Dialog", "+"))
        self.pushButton_11.setText(_translate("Dialog", "<="))
        self.pushButton_13.setText(_translate("Dialog", "/"))
        self.pushButton_10.setText(_translate("Dialog", "C"))
        self.pushButton_12.setText(_translate("Dialog", "sqrt"))
        self.pushButton_17.setText(_translate("Dialog", "0"))
        self.pushButton_18.setText(_translate("Dialog", "."))
        self.pushButton_19.setText(_translate("Dialog", "="))
        self.pushButton_20.setText(_translate("Dialog", "+/-"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
